"""Generate self-hosted repo cards (repo-<name>.svg) from the GitHub REST API.

Replaces the third-party pin service (github-readme-stats-*.vercel.app),
which fails with "Maximum retries exceeded" when its PAT quota is gone.
These cards live in this repo, match the cream/espresso brand, and each
card is wrapped in its own <a> in README so it stays clickable.

Usage:
    python .github/scripts/update_cards.py          # all featured repos
    python .github/scripts/update_cards.py openclaw # single repo

Env:
    GITHUB_TOKEN / GH_TOKEN (CI provides it; works unauthenticated too)
    GITHUB_REPOSITORY (owner derived from it, default Officialpotatoxsudo)
"""
from __future__ import annotations

import datetime as dt
import html
import json
import os
import re
import sys
import urllib.request

API = "https://api.github.com"
FEATURED = ["openclaw", "Nist_update", "slapfx_release"]

LANG_COLORS = {
    "TypeScript": "#3178C6",
    "Python": "#3776AB",
    "Kotlin": "#A97BFF",
    "Dart": "#54C5F8",
    "JavaScript": "#F7DF1E",
    "Go": "#00ADD8",
    "Rust": "#DEA584",
    "HTML": "#E34F26",
    "C++": "#00599C",
    "CMake": "#064F8C",
    "Markdown": "#58a6ff",
    "Shell": "#89e051",
}

_EMOJI = re.compile(
    "[\U0001F300-\U0001FAFF\u2600-\u27BF\u2B00-\u2BFF\uFE0F\u200D"
    "\U0001F000-\U0001F2FF\U0001F600-\U0001F64F\U0001F680-\U0001F6FF"
    "\u2190-\u21FF\u2300-\u23FF]"
)


def _headers() -> dict:
    h = {"Accept": "application/vnd.github+json",
         "User-Agent": "profile-cards-updater"}
    tok = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    if tok:
        h["Authorization"] = f"Bearer {tok}"
    return h


def _get_json(url: str):
    req = urllib.request.Request(url, headers=_headers())
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read().decode("utf-8"))


def clean(text: str | None, fallback: str) -> str:
    """Strip emoji (zero-emoji profile), collapse whitespace, XML-escape."""
    if not text:
        return fallback
    text = _EMOJI.sub("", text)
    text = re.sub(r"\s+", " ", text).strip()
    # keep the words, drop a dangling "way ." left by a stripped glyph
    text = re.sub(r"\s+([.,;:!?])", r"\1", text)
    return html.escape(text) or fallback


def wrap(text: str, width: int = 44, lines: int = 2) -> list[str]:
    words, out, cur = text.split(" "), [], ""
    for w in words:
        nxt = f"{cur} {w}".strip()
        if len(nxt) <= width:
            cur = nxt
        elif len(out) < lines - 1:
            out.append(cur)
            cur = w
        else:
            cur = nxt
            break
    if cur:
        out.append(cur)
    out = out[:lines]
    flat = " ".join(text.split(" "))
    if len(" ".join(out)) < len(flat):
        out[-1] = out[-1][: width - 1].rstrip() + "…"
    return out


CARD = """<svg xmlns="http://www.w3.org/2000/svg" width="440" height="168" viewBox="0 0 440 168" role="img" aria-label="{name} repo card">
  <!-- self-hosted repo card · regenerated by update_cards.py · {date} -->
  <defs>
    <linearGradient id="racc" x1="0" y1="0" x2="1" y2="0" gradientUnits="objectBoundingBox">
      <stop offset="0%" stop-color="#FBF3E0"/><stop offset="55%" stop-color="#F0D9A8"/><stop offset="100%" stop-color="#D3A05F"/>
      <animateTransform attributeName="gradientTransform" type="translate" values="-1 0;0 0;-1 0" dur="9s" repeatCount="indefinite"/>
    </linearGradient>
    <clipPath id="rclip"><rect x="1" y="1" width="438" height="166" rx="16"/></clipPath>
  </defs>
  <style>
    .t{{font-family:"SFMono-Regular",Consolas,"Fira Code",monospace;font-size:19px;font-weight:700;fill:url(#racc);}}
    .d{{font-family:"SFMono-Regular",Consolas,"Fira Code",monospace;font-size:13px;fill:#A89A83;}}
    .m{{font-family:"SFMono-Regular",Consolas,"Fira Code",monospace;font-size:13px;fill:#F3E9D2;}}
    .tag{{font-family:"SFMono-Regular",Consolas,"Fira Code",monospace;font-size:11px;fill:#D3A05F;}}
  </style>
  <rect x="1" y="1" width="438" height="166" rx="16" fill="#171310" stroke="#3D3227"/>
  <rect x="1" y="1" width="438" height="6" rx="3" fill="url(#racc)"/>
  <g clip-path="url(#rclip)" opacity="0.4">
    <rect x="-80" y="1" width="80" height="6" fill="#FBF3E0" opacity="0.4">
      <animate attributeName="x" from="-80" to="438" dur="4s" begin="{delay}s" repeatCount="indefinite"/>
    </rect>
  </g>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" dur="0.4s" begin="0.05s" fill="freeze"/>
    <text x="26" y="52" class="t">{name}</text>{fork_tag}
  </g>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" dur="0.4s" begin="0.2s" fill="freeze"/>
{desc_lines}
  </g>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" dur="0.4s" begin="0.35s" fill="freeze"/>
    <circle cx="32" cy="128" r="6" fill="{lang_color}"/>
    <text x="46" y="133" class="m">{lang}</text>
    <g transform="translate(200,128)" fill="#E7C078">
      <polygon points="0,-8 2.4,-2.7 7.6,-2.5 3.8,1.2 5.9,6.5 0,3.4 -5.9,6.5 -3.8,1.2 -7.6,-2.5 -2.4,-2.7"/>
    </g>
    <text x="214" y="133" class="m">{stars}</text>
    <text x="414" y="133" class="d" text-anchor="end">{pushed}</text>
  </g>
</svg>
"""


def render_card(repo: dict, idx: int) -> str:
    name = repo["name"]
    desc = wrap(clean(repo.get("description"), "no description yet"))
    desc_lines = "\n".join(
        f'    <text x="26" y="{82 + i * 22}" class="d">{line}</text>'
        for i, line in enumerate(desc)
    )
    lang = repo.get("language") or "empty"
    fork_tag = ""
    if repo.get("fork"):
        # place tag right after the name (~11.5px per char at 19px bold mono)
        x = 26 + int(len(name) * 11.5) + 14
        fork_tag = (
            f'\n    <rect x="{x}" y="34" width="46" height="20" rx="6" '
            f'fill="none" stroke="#D3A05F"/>'
            f'\n    <text x="{x + 23}" y="48" class="tag" text-anchor="middle">fork</text>'
        )
    pushed = dt.datetime.strptime(
        repo["pushed_at"], "%Y-%m-%dT%H:%M:%SZ").strftime("%b %Y").lower()
    return CARD.format(
        name=html.escape(name),
        fork_tag=fork_tag,
        desc_lines=desc_lines,
        lang=html.escape(lang),
        lang_color=LANG_COLORS.get(lang, "#6F6350"),
        stars=repo.get("stargazers_count", 0),
        pushed=pushed,
        date=dt.date.today().isoformat(),
        delay=idx,
    )


def main(argv: list[str]) -> int:
    owner = os.environ.get("GITHUB_REPOSITORY",
                           "Officialpotatoxsudo/Officialpotatoxsudo").split("/")[0]
    targets = [a for a in argv if not a.startswith("-")] or FEATURED
    changed: list[str] = []
    for i, name in enumerate(targets):
        try:
            repo = _get_json(f"{API}/repos/{owner}/{name}")
        except Exception as e:  # noqa: BLE001 — fail loudly but readably
            print(f"card {name} failed: {e}", file=sys.stderr)
            return 1
        path = f"repo-{name.lower()}.svg"
        svg = render_card(repo, i)
        try:
            old = open(path, encoding="utf-8").read()
        except FileNotFoundError:
            old = ""
        if old != svg:
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(svg)
            changed.append(path)
        print(f"{path}: stars={repo.get('stargazers_count')} "
              f"lang={repo.get('language')} fork={repo.get('fork')}")
    print("updated:", changed or "already fresh")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
