"""Render a self-hosted activity card (activity.svg) from real contribution data.

Source: GraphQL contributionCalendar (trailing year). Shows the year total
plus one bar per week for the last 12 weeks — no streak number, so the card
reads honest at any activity level.

Usage:
    python .github/scripts/update_activity.py

Env:
    GITHUB_TOKEN / GH_TOKEN (Actions provides it; without one a same-chrome
    placeholder card is written instead of failing the job)
    GITHUB_REPOSITORY (owner derived from it)
"""
from __future__ import annotations

import datetime as dt
import json
import os
import sys
import urllib.request

API = "https://api.github.com/graphql"
TARGET = "activity.svg"

QUERY = """
query($login: String!) {
  user(login: $login) {
    contributionsCollection {
      contributionCalendar {
        totalContributions
        weeks { contributionDays { contributionCount } }
      }
    }
  }
}
"""

# empty -> full, espresso-safe bronze ramp
RAMP = ["#2A2118", "#6B5233", "#A3703D", "#D9A95F", "#F0D9A8"]


def _token() -> str | None:
    return os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")


def fetch(login: str) -> tuple[int, list[int]]:
    body = json.dumps({"query": QUERY, "variables": {"login": login}}).encode()
    req = urllib.request.Request(
        API, data=body,
        headers={"Authorization": f"Bearer {_token()}",
                 "Content-Type": "application/json",
                 "User-Agent": "profile-activity-updater"},
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        data = json.loads(r.read().decode("utf-8"))
    if "errors" in data:
        raise RuntimeError(data["errors"][0].get("message", "graphql error"))
    cal = data["data"]["user"]["contributionsCollection"]["contributionCalendar"]
    weeks = [sum(d["contributionCount"] for d in w["contributionDays"])
             for w in cal["weeks"]][-12:]
    return cal["totalContributions"], weeks


def shade(value: int, peak: int) -> str:
    if value <= 0 or peak <= 0:
        return RAMP[0]
    q = min(3, (value - 1) * 4 // peak)
    return RAMP[q + 1]


CARD = """<svg xmlns="http://www.w3.org/2000/svg" width="680" height="230" viewBox="0 0 680 230" role="img" aria-label="activity">
  <!-- self-hosted activity card · regenerated by update_activity.py · {date} -->
  <defs>
    <linearGradient id="acream" x1="0" y1="0" x2="1" y2="0" gradientUnits="objectBoundingBox">
      <stop offset="0%" stop-color="#FBF3E0"/><stop offset="55%" stop-color="#F0D9A8"/><stop offset="100%" stop-color="#D3A05F"/>
      <animateTransform attributeName="gradientTransform" type="translate" values="-1 0;0 0;-1 0" dur="9s" repeatCount="indefinite"/>
    </linearGradient>
    <clipPath id="aclip"><rect x="1" y="1" width="678" height="228" rx="16"/></clipPath>
  </defs>
  <style>
    .t{{font-family:"SFMono-Regular",Consolas,"Fira Code",monospace;font-size:21px;font-weight:700;fill:#F7ECD4;}}
    .n{{font-family:"SFMono-Regular",Consolas,"Fira Code",monospace;font-size:34px;font-weight:700;fill:#F7ECD4;}}
    .s{{font-family:"SFMono-Regular",Consolas,"Fira Code",monospace;font-size:12px;fill:#7A6C55;}}
  </style>
  <rect x="1" y="1" width="678" height="228" rx="16" fill="#171310" stroke="#3D3227"/>
  <rect x="1" y="1" width="678" height="6" rx="3" fill="url(#acream)"/>
  <g clip-path="url(#aclip)" opacity="0.4">
    <rect x="-80" y="1" width="80" height="6" fill="#FBF3E0" opacity="0.4">
      <animate attributeName="x" from="-80" to="678" dur="5s" begin="0.5s" repeatCount="indefinite"/>
    </rect>
  </g>
  <g opacity="0">
    <animate attributeName="opacity" from="0" to="1" dur="0.4s" begin="0.05s" fill="freeze"/>
    <text x="26" y="52" class="t">Activity</text>
    <text x="654" y="52" class="s" text-anchor="end">last 12 weeks</text>
    <text x="26" y="100" class="n">{total}</text>
    <text x="26" y="120" class="s">contributions · trailing year</text>
  </g>
  <g>
{bars}
  </g>
  <text x="26" y="216" class="s">updated {date} · {owner}</text>
</svg>
"""

PLACEHOLDER = """<svg xmlns="http://www.w3.org/2000/svg" width="680" height="230" viewBox="0 0 680 230" role="img" aria-label="activity">
  <defs>
    <linearGradient id="acream" x1="0" y1="0" x2="1" y2="0" gradientUnits="objectBoundingBox">
      <stop offset="0%" stop-color="#FBF3E0"/><stop offset="55%" stop-color="#F0D9A8"/><stop offset="100%" stop-color="#D3A05F"/>
    </linearGradient>
  </defs>
  <style>
    .t{{font-family:"SFMono-Regular",Consolas,"Fira Code",monospace;font-size:21px;font-weight:700;fill:#F7ECD4;}}
    .s{{font-family:"SFMono-Regular",Consolas,"Fira Code",monospace;font-size:12px;fill:#7A6C55;}}
  </style>
  <rect x="1" y="1" width="678" height="228" rx="16" fill="#171310" stroke="#3D3227"/>
  <rect x="1" y="1" width="678" height="6" rx="3" fill="url(#acream)"/>
  <text x="26" y="52" class="t">Activity</text>
  <text x="340" y="140" class="s" text-anchor="middle">fills in on the next CI run (needs GITHUB_TOKEN)</text>
</svg>
"""


def render(total: int, weeks: list[int], owner: str) -> str:
    peak = max(weeks) if weeks else 0
    base, top, cell, bw = 196, 86, 52, 34
    bars = []
    for i, v in enumerate(weeks):
        h = 8 if v <= 0 else max(14, round((v / peak) * (base - top)))
        x = 30 + i * cell + (cell - bw) // 2
        bars.append(
            f'    <rect x="{x}" y="{base - h}" width="{bw}" height="{h}" rx="6" fill="{shade(v, peak)}">'
            f'<animate attributeName="height" from="0" to="{h}" dur="0.6s" '
            f'begin="{0.15 + i * 0.06:.2f}s" fill="freeze"/>'
            f'<animate attributeName="y" from="{base}" to="{base - h}" dur="0.6s" '
            f'begin="{0.15 + i * 0.06:.2f}s" fill="freeze"/>'
            f"<title>{v} contributions</title></rect>"
        )
    return CARD.format(total=f"{total:,}", bars="\n".join(bars),
                       date=dt.date.today().isoformat(), owner=owner)


def main() -> int:
    owner = os.environ.get("GITHUB_REPOSITORY",
                           "Officialpotatoxsudo/Officialpotatoxsudo").split("/")[0]
    if _token():
        try:
            total, weeks = fetch(owner)
            svg = render(total, weeks, owner)
            print(f"activity: total={total} weeks={weeks}")
        except Exception as e:  # noqa: BLE001 — never fail the job on stats
            print(f"activity fetch failed ({e}); writing placeholder",
                  file=sys.stderr)
            svg = PLACEHOLDER
    else:
        print("no token; writing placeholder", file=sys.stderr)
        svg = PLACEHOLDER
    try:
        old = open(TARGET, encoding="utf-8").read()
    except FileNotFoundError:
        old = ""
    if old != svg:
        with open(TARGET, "w", encoding="utf-8", newline="\n") as f:
            f.write(svg)
        print(f"{TARGET} updated")
    else:
        print(f"{TARGET} already fresh")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
